title: "Your Awesome Title"
name: "Duru"
email: metinzorlu@msn.com 
description: Ki≈üisel blog

baseurl: "/duru" 
url: "" 
twitter_username: deruni
github_username: mtnzorlu

theme: duru


plugins:
  - jekyll-feed
  - jekyll-seo-tag
