title: "Code 64"
name: "Duru"
email: metinzorlu@msn.com 
description: Ki≈üisel blog

baseurl: "duru" 
url: "" 
twitter_username: deruni
github_username: mtnzorlu


plugins:
  - jekyll-feed
  - jekyll-seo-tag
